version: '3.8'

services:
  configsvr1:
    image: mongo:6.0
    command: mongod --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - configsvr1:/data/db
    networks:
      - shardnet

  configsvr2:
    image: mongo:6.0
    command: mongod --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    ports:
      - "27020:27017"
    volumes:
      - configsvr2:/data/db
    networks:
      - shardnet

  configsvr3:
    image: mongo:6.0
    command: mongod --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    ports:
      - "27021:27017"
    volumes:
      - configsvr3:/data/db
    networks:
      - shardnet

 
  shard1a:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --bind_ip_all
    ports:
      - "27022:27017"
    volumes:
      - shard1a:/data/db
    networks:
      - shardnet

  shard1b:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --bind_ip_all
    ports:
      - "27023:27017"
    volumes:
      - shard1b:/data/db
    networks:
      - shardnet


  shard2a:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27024:27017"
    volumes:
      - shard2a:/data/db
    networks:
      - shardnet

  shard2b:
    image: mongo:6.0
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27025:27017"
    volumes:
      - shard2b:/data/db
    networks:
      - shardnet


  mongos:
    image: mongo:6.0
    command: mongos --configdb configReplSet/configsvr1:27017,configsvr2:27017,configsvr3:27017 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1a
      - shard1b
      - shard2a
      - shard2b
    networks:
      - shardnet

volumes:
  configsvr1:
  configsvr2:
  configsvr3:
  shard1a:
  shard1b:
  shard2a:
  shard2b:

networks:
  shardnet:
    driver: bridge